name: codelab_app_workspace

packages:
  - apps/**
  - packages/**

scripts:
  bootstrap:
    description: Install dependencies for all packages via FVM Flutter SDK
    run: |
      melos exec -c 4 -- fvm flutter pub get

  clean:
    description: Clean build artifacts in all packages
    run: |
      melos exec -c 4 -- fvm flutter clean

  analyze:
    description: Run static analysis for all packages
    run: |
      melos exec -c 4 -- fvm flutter analyze

  format:
    description: Format Dart code in all packages
    run: |
      melos exec -- fvm dart format .

  test:
    description: Run tests for all packages
    run: |
      melos exec -c 2 -- fvm flutter test
