name: codelab_app_workspace
publish_to: none

environment:
  sdk: ^3.11.5

workspace:
  - apps/codelab_desktop
  - apps/codelab_ui_widgetbook
  - packages/codelab_ui_components
  
dev_dependencies:
  melos: ^7.5.1
