name: codelab_ui_widgetbook
description: "Widgetbook showcase for CodeLab UI Components"
publish_to: none

environment:
  sdk: ^3.11.5
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0
  fluent_ui: ^4.15.1
  codelab_ui_components:
    path: ../../packages/codelab_ui_components

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.14.1
  widgetbook_generator: ^3.8.1

flutter:
  uses-material-design: true
